### ISSUE TITLE
Signup throws "invalid credential" on first submit 

### ISSUE THREAD

**Issue by she0305** [calcom/platform-starter-kit#36]
### Description
When deployed with the platform-starter-kit, the create account page only works with the second click. When you hit "Create an account" for the first time, it shows "invalid credential". Then if you hit login again, it finally takes you to the next step. This happens with my deployed app, and I just confirmed that it also happens on your example app: https://experts.cal.com/signup
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/96fe8076-54e6-4c32-bfa3-33a02a4a2b48">

**Comment by supalarry** [comment]
Thank you for reporting the issues! Fixed by #42
