### ISSUE TITLE
[https://experts.cal.com/]  Application error: a server-side exception has occurred (see the server logs for more information).

### ISSUE THREAD

**Issue by she0305** [calcom/platform-starter-kit#37]
Confirming that this server-side exception is also happening in the official demo web: https://experts.cal.com/.
When you create an account without finishing the workflow, and try to access to Dashboard, the server crashes.

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/4914396d-a363-4a7a-9baa-c8504895b3ba">

**Comment by supalarry** [comment]
Fixed by #42 - I could access dashboard without errors.
